name: Format

on: pull_request

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build

      - name: Format
        run: docker-compose run --rm app /bin/bash -c "yarn format:check"
